image:
  tag: "0d6016c"
  pullPolicy: Always
replicaCount: 2
rbac:
  create: true  
app:
  greetingMessage: "dev-change"
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: dev.cch.com
      paths:
        - path: /api/dev(/|$)(.*)
          pathType: Prefix