image:
  tag: "0d6016c"
  pullPolicy: Always
rbac:
  create: true  
app:
  greetingMessage: "prod"
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: prod.cch.com
      paths:
        - path: /api/prod(/|$)(.*)
          pathType: Prefix