apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
  - default:
      cpu: 100m
      memory: 512Mi
    defaultRequest:
      cpu: 50m
      memory: 128Mi
    type: Container