apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    requests.cpu: "300m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    pods: "3"