kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kubernetes-api.fullname" . }}
  labels:
    {{- include "kubernetes-api.labels" . | nindent 4 }}
data:
  application.properties: |-
    {{- tpl (.Files.Get "config/app.conf") . | nindent 4 }}
