apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
 env: dev
commonAnnotations:
  team: "team-b"
namespace: team-b

bases:
- ../../../base

patches:
- target:
    kind: Namespace
    name: dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-b
- target:
    kind: ResourceQuota
    name: resource-quota
  patch: |-
    - op: replace
      path: /metadata/name
      value: quota-team-b
- target:
    kind: LimitRange
    name: limit-range
  patch: |-
    - op: replace
      path: /metadata/name
      value: limit-team-b
    - op: replace
      path: /spec/limits/0/defaultRequest/cpu
      value: 100m